4-6 数字の文字列操作のやつを実装しました
mine2424/lesson01 pull request #12
Opened 2020-06-21 06:49 UTC by mine2424

2020-06-25 06:05 UTC, masashi0508 requested changes
このままだと動きません。

2020-06-25 06:05 UTC, masashi0508 commented on 4-6/main.js
>  const nowTime = process.argv.slice(2).join(" ")
文字列を配列にして文字列にしています。
const nowTime = process.argv[2];
これと同じです。

2020-06-25 06:05 UTC, masashi0508 commented on 4-6/main.js
> +        output(test,result)
第一変数のtestとは？
ここはmodelHoursだと思います。

2020-06-25 10:32 UTC, masashi0508 approved these changes
LGTM

2020-06-28 00:35 UTC, mayu11122 approved these changes

2020-06-29 04:44 UTC, merged